# Generated by Django 5.1.3 on 2024-12-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_end_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_completion',
        ),
    ]
